In [14]:
from utils.objaverse_dataset import ObjaversePointCloudDataset

annotations_file = '/Users/kostyalbalint/Documents/Egyetem/7.Felev/Szakdolgozat/objaverse_labeling/concatenated_annotations.npy'
pc_dir = '/Users/kostyalbalint/Documents/Egyetem/7.Felev/Szakdolgozat/pointCloudsNoColor'

dataset = ObjaversePointCloudDataset(annotations_file=annotations_file, pc_dir=pc_dir, split=None, scale_mode='shape_bbox', name_filter=None, load_to_mem=False)

In [2]:
dataset.__len__()

631421

In [7]:
import torch

def sum_vector_lengths(tensor):    
    vector_lengths = torch.sqrt(torch.sum(tensor ** 2, dim=1))
    sum_lengths = torch.sum(vector_lengths)
    return sum_lengths

In [17]:
lengths = []
for id in range(10):
    lengths.append(sum_vector_lengths(dataset[id]['pointcloud']))

In [16]:
import plotly.graph_objects as go

def show_point_cloud(points, color, title):
    # Create a 3D scatter plot
    fig = go.Figure()

    # Scatter plot of the points
    fig.add_trace(go.Scatter3d(
        x=points[:, 0],
        y=points[:, 1],
        z=points[:, 2],
        mode='markers',
        marker=dict(
            size=2,
            color=color,  # You can customize the color here
        )
    ))

    # Set layout options
    fig.update_layout(scene=dict(
        xaxis_title='X-axis',
        yaxis_title='Y-axis',
        zaxis_title='Z-axis'),
        title=title)

    # Show the plot
    return fig.show()

show_point_cloud(dataset[4]['pointcloud'], 'red', '')

In [18]:
lengths

[tensor(7675.4258),
 tensor(3815.4668),
 tensor(6192.9321),
 tensor(7053.5010),
 tensor(7400.9258),
 tensor(5511.1133),
 tensor(5862.4106),
 tensor(6392.7764),
 tensor(6310.6440),
 tensor(6876.2588)]

In [41]:
paths = []
for id in range(dataset.__len__()):
    paths.append(dataset.get_file_path(id).replace(pc_dir + "/", ""))

In [62]:
paths

  0%|          | 0/789276 [00:00<?, ?it/s]

In [43]:
import os
import shutil

destination_directory = '/Users/kostyalbalint/Documents/Egyetem/7.Felev/Szakdolgozat/pointCloudsSplit/knife'

for file_path in paths:
    # Construct the full source and destination paths
    source_path = os.path.join(pc_dir, file_path)
    destination_path = os.path.join(destination_directory, file_path)

    # Ensure the destination directory exists, and copy the file
    os.makedirs(os.path.dirname(destination_path), exist_ok=True)
    shutil.copy2(source_path, destination_path)

print("Files have been copied to the destination directory.")


[array([[ 0.05864505, -0.02573038,  1.28947592],
        [-0.75293744, -0.02573039,  1.23491228],
        [ 1.94353187,  0.01324196, -1.53363514],
        ...,
        [ 1.45763147,  0.02426911, -1.86546373],
        [ 0.09132042, -0.0257309 , -1.91840076],
        [-1.10286462, -0.02573084, -1.54451311]]),
 array([[-13.52879143, -42.93766403, -17.21154404],
        [ -2.41799664, -44.8401947 ,  31.37168121],
        [ -0.86769927, -40.87131882, -30.84964943],
        ...,
        [ -0.21904336, -42.88376617, -78.18962097],
        [-10.00971794, -40.80188751,  -4.84957504],
        [ 12.69331169, -44.38183594,  -9.10169697]]),
 array([[-0.45716929,  0.66442156,  0.11179254],
        [-0.01390182, -0.07654251,  0.11447766],
        [-0.33860576,  0.26097763,  0.07698057],
        ...,
        [ 0.06623167, -0.83226609,  0.11418586],
        [ 0.13300771, -0.75850761,  0.07716215],
        [-0.23709223, -0.56685394, -0.09939837]]),
 array([[ 108.17337036,   41.29547501,   30.88544083],
